name: Greeting from Mona
on:
  push:
    branches:
      - master
jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: "李"
          MIDDLE_NAME: "三"
          LAST_NAME: "四"
        run: |
          echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME
